config/routes.rb
Rails.application.routes.draw do

  

  get 'users/login' => 'users#login'

  post 'users/login' => 'users#auth'

  get 'users/logout' => 'users#logout'

  get 'tasks/search' => 'tasks#search'

  get 'tasks/search_results' => 'tasks#search_results'

  get 'users/signup' => 'users#new'

  resources :tasks

  resources :lists

  resources :tags

  resources :users

  root 'lists#index'

end

app/models/list.rb
class List < ActiveRecord::Base
	has_many :tasks, dependent: :destroy
	belongs_to :user

	validates :name, presence: true
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :valid_auth
  before_action :set_list, only: [:show, :edit, :update, :destroy]


  # GET /lists
  # GET /lists.json
  def index
    @lists = List.where(user_id: @user.id)
    @list = List.new
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @task = Task.new
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)
    @list.user_id = @user.id

    respond_to do |format|
      if @list.save
        format.html { redirect_to lists_path, notice: "List " + list_params["name"] + ' was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to lists_path, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
      if @list.user_id != @user.id
        redirect_to lists_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name)
    end

    def valid_auth
      if session[:logged_in?]
        @user = User.find(session[:user_id])
      else
        redirect_to users_login_path, notice: "You must login to access your lists."
      end
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_for(@list, html: {class: "form-inline"}) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <br />

  <div class="form-group">
    <%= f.label :name, "List:" %>
    <%= f.text_field :name, class: "form-control" %>
    <%= f.submit class: "btn btn-primary", "aria-hidden" => "true" %>
  </div>

  <br>

  <div class="actions">
    
  </div>


<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form' %>

app/views/lists/index.html.erb
<h1>All Lists</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th class="lead">Name</th>
      <th class="lead">Options</th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.name %></td>
        <td><%= link_to ' SHOW TASKS', list, class: "btn btn-primary" %>
        <%= link_to ' EDIT', edit_list_path(list), class: "btn btn-warning" %>
        <%= link_to ' DELETE', list, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>



<%= field_set_tag "New List" do %>
  <%= render 'form' %>
<% end %>

<br>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form' %>

app/views/lists/show.html.erb
<h3>
  <strong></strong>
  <%= @list.name %>
</h3>

<br>

<table class="table table-striped">
  <thead>
    <tr>
      <th class="lead">Tasks</th>
      <th class="lead">Options</th>
      <th class="lead">Tags</th>
      <th class="lead">Status</th>

    </tr>
  </thead>

  <tbody>
    <% @list.tasks.each do |task| %>
      <tr>
        <td class="lead"><%= task.name %></td>
        <td>
        <%= link_to ' EDIT', edit_task_path(task), class: "btn btn-warning" %>
        <%= link_to ' DELETE', task, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
        <td>
          <% task.tags.each do |t| %>
          <%= link_to t.name+',', tag_path(t), class: "lead" %>
          <% end %>
        </td>
        <td>
          <% if task.isStarred %>
          <span class="glyphicon glyphicon-star"></span>
          <% end %>
          <% if task.isDone %>
          <span class="glyphicon glyphicon-ok"></span>
          <% end %>
          <% if task.isArchived %>
          <span class="glyphicon glyphicon-inbox"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

  <%= render 'tasks/form' %>