config/routes.rb
Rails.application.routes.draw do

  

  get 'users/login' => 'users#login'

  post 'users/login' => 'users#auth'

  get 'users/logout' => 'users#logout'

  get 'tasks/search' => 'tasks#search'

  get 'tasks/search_results' => 'tasks#search_results'

  get 'users/signup' => 'users#new'

  resources :tasks

  resources :lists

  resources :tags

  resources :users

  root 'lists#index'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :lists, dependent: :destroy

	validates :password_confirmation, presence: true

	validates :username, uniqueness: true
  	validates_confirmation_of :password

  	validates :password, length: {
  		minimum: 6
  	}

  	validates :username, length: {
  		minimum: 6
  	}



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def login
  end

  def auth
    uname = user_params["username"]
    upass = user_params["password"]

    @users = User.where(username: uname)
    if (@users.count > 0)
      @user = @users.first
      if (@user.password == upass)
        session[:logged_in?] = true
        session[:user] = @user
        session[:user_id] = @user.id
        session[:user_name] = @user.name
        redirect_to lists_path
      else
        redirect_to users_login_path, notice: "Incorrect Password."
      end
    else
      redirect_to users_login_path, notice: "Incorrect Username."
    end
  end

  def signup
  end

  def logout
    reset_session
    redirect_to users_login_path, notice: "You have successfully logged out."
  end

  # GET /users
  # GET /users.json
  def index
    # redirect to edit user's information page
    @user = User.find(session[:user_id])
    redirect_to edit_user_path(@user)
  end

  # GET /users/1
  # GET /users/1.json
  def show
    # should not visit this page but if it does then redirect to users's tasks
    redirect_to lists_path
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    if @user.id != session[:user_id]
      redirect_to users_path, notice: "You can't edit someone else's profile. Please edit your own."
    end
  end

  # POST /users
  # POST /users.json
  def create

    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to lists_path, notice: @user.name + ', you successfully created an account.' }
        format.json { render :show, status: :created, location: @user }

        session[:logged_in?] = true
        session[:user] = @user
        session[:user_id] = @user.id
        session[:user_name] = @user.name

      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Changes updated' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :username, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <br>

  <div class="form-group">
    <%= f.label :Name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :Username %><br>
    <%= f.text_field :username, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :Password %><br>
    <%= f.password_field :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label 'Re-Password' %><br>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Update User Information</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Listing Users!!!!</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/login.html.erb
<h2>Login to access your tasks or <a href="/users/signup/"><u>Sign Up</u></a></h2>

<br>

<%= form_for :user do |f| %>

  <div class="form-inline form-group">
    <%= f.label :Username %><br>
    <%= f.text_field :username, class: "form-control" %>
  </div>

  <div class="form-inline form-group">
    <%= f.label :Password %><br>
    <%= f.password_field :password, class: "form-control" %>
  </div>


  <div class="actions form-group">
    <%= f.submit(:Login, class: "btn btn-primary") %>
  </div>

  <br>

  <div class="demo">
    <p class="lead">For a demo, you can login using username 'testuser' and password 'testpass'</p>
  </div>

<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>


<%= link_to 'Back', tasks_path %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>