config/routes.rb
Rails.application.routes.draw do

  

  get 'users/login' => 'users#login'

  post 'users/login' => 'users#auth'

  get 'users/logout' => 'users#logout'

  get 'tasks/search' => 'tasks#search'

  get 'tasks/search_results' => 'tasks#search_results'

  get 'users/signup' => 'users#new'

  resources :tasks

  resources :lists

  resources :tags

  resources :users

  root 'lists#index'

end

app/models/tag.rb
class Tag < ActiveRecord::Base
	belongs_to :task
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :valid_auth
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  def search
  	@tag_name = params[:tag_name]
  	@tags = Tag.where(name: @tag_name)
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @tags = Tag.where(name: @tag.name)
  end

  # GET /tags/new
  def new
    redirect_to tags_path
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name, :task_id)
    end

    def valid_auth
      if session[:logged_in?]
        @user = User.find(session[:user_id])
      else
        redirect_to users_login_path, notice: "You must login to access your tasks."
      end
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_for(@tag, html: {class: "form-inline"}) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form' %>

app/views/tags/index.html.erb
<h1>Listing Tags</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th class="lead">Name</th>
      <th class="lead">Options</th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
    <% if (tag.task.list.user_id == session[:user_id]) %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= link_to ' SHOW TASKS', tag, class: "btn btn-primary" %>
        <%= link_to ' EDIT', edit_task_path(tag), class: "btn btn-warning" %>
        <%= link_to ' DELETE', tag, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<br>

<%= render 'form' %>

app/views/tags/search.html.erb
<p id="notice"><%= notice %></p>

<h1>Search Tags</h1>

<table>
  <thead>
    <tr>
    <% if (@tags.count > 0) %>
      <th>Tasks with tag: '<%= @tag_name %>'</th>
      <% else %>
      <th>No tasks with tag: '<%= @tag_name %>'</th>
      <% end %>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <% @tags.each do |tag| %>
      <% if (tag.task.list.user_id == session[:user_id]) %>
      <tr>  
        <td><%= link_to tag.task.name, tag.task %></td>
        <td><%= link_to 'Show', tag.task %></td>
        <td><%= link_to 'Edit', edit_task_path(tag.task) %></td>
        <td><%= link_to 'Destroy', tag.task, method: :delete, data: { confirm: 'Are you sure?' } %></td> 
      </tr>
      <% end %>
    <% end %>

  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/show.html.erb
<h2>Tasks with tag '<%= @tag.name %>'</h2>
<br>

<table class="table table-striped">
  <thead>
    <tr>
      <th class="lead">Name</th>
      <th class="lead">List</th>
      <th class="lead">Options</th>
      <th class="lead">Tags</th>
      <th class="lead">Status</th>
    </tr>
  </thead>

  <tbody>
  <% if (@tags.count > 0) %>
    <% @tags.each do |tag| %>
      <% if (tag.task.list.user_id == session[:user_id]) %>
      <tr>  
        <td class="lead"><%= tag.task.name %></td>
        <td class="lead"><%= link_to tag.task.list.name, tag.task.list %></td>
        <td>
        <%= link_to ' EDIT', edit_task_path(tag.task), class: "btn btn-warning" %>
        <%= link_to ' DELETE', tag.task, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
        <td>
          <% tag.task.tags.each do |t| %>
          <%= link_to t.name+',', tag_path(t), class: "lead" %>
          <% end %>
        </td>
        <td>
          <% if tag.task.isStarred %>
          <span class="glyphicon glyphicon-star"></span>
          <% end %>
          <% if tag.task.isDone %>
          <span class="glyphicon glyphicon-ok"></span>
          <% end %>
          <% if tag.task.isArchived %>
          <span class="glyphicon glyphicon-inbox"></span>
          <% end %>
        </td>
      </tr>
      <% end %>
    <% end %>
  <% else %>
    <p>No tasks to show! Make a new one.</p>
  <% end %>
  </tbody>
</table>