config/routes.rb
Rails.application.routes.draw do

  

  get 'users/login' => 'users#login'

  post 'users/login' => 'users#auth'

  get 'users/logout' => 'users#logout'

  get 'tasks/search' => 'tasks#search'

  get 'tasks/search_results' => 'tasks#search_results'

  get 'users/signup' => 'users#new'

  resources :tasks

  resources :lists

  resources :tags

  resources :users

  root 'lists#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Todo</title>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">		
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
		
	</head>
	<body>
		<div class="container">
			<div class="container">
				<div class="navbar">
					<div class="navbar-inner">
						<ul class="nav nav-tabs">
							<% if session[:logged_in?] %>
							<li class="lead"><a href=<%= lists_path %>>Lists</a></li>
							<li class="lead"><a href=<%= tasks_path %>>Tasks</a></li>
							<li class="lead"><a href=<%= tasks_search_path %>>Search Tasks</a></li>
							<li class="lead"><a href=<%= tags_path %>>Tags</a></li>
							<li class="pull-right lead"><a href=<%= users_logout_path %>>Logout</a></li>
							<li class="pull-right lead"><a href=<%= users_path %>>Welcome <%= session[:user_name] %>!</a></li>
							<% else  %>
							<li class="pull-right lead"><a href=<%= users_login_path %>>Login<span class="glyphicon glyphicon-login"></span></a></li>
							<li class="pull-right lead"><a href=<%= users_signup_path %>>Sign Up</a></li>
							<% end %>
						</ul>
					</div>
				</div>
			</div>
			<% if notice %>
			<p id="notice" class="alert alert-success lead"><%= notice %></p><br>
			<% end %>
			<%= yield %>
		</div>
	</body>
</html>